name: HACS validation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Validate HACS
        uses: "hacs/action@main"
        with:
          category: "plugin"